### ISSUE TITLE
Where to find OTAIntegratedTestingHelper.zip

### ISSUE THREAD

**Issue by Cesar4D** [Embarcadero/OTAPI-Docs#2]
Hello, congratulations for the content.
I would like to know where I can find the OTAIntegratedTestingHelper.zip file located in The Delphi IDE Open Tools API - Version 1.2.docx file

Thanks

**Comment by DGH2112** [comment]
It can be found at [https://github.com/DGH2112/Integrated-Testing-Helper](https://github.com/DGH2112/Integrated-Testing-Helper).
