### ISSUE TITLE
Splash screen icon size 48x48 vs documented 24x24

### ISSUE THREAD

**Issue by darianmiller** [Embarcadero/OTAPI-Docs#3]
See reference article:
https://www.davidghoyle.co.uk/WordPress/?p=1256

The XML help for `IOTAAboutBoxServices120.AddPluginInfo` says `The Image should follow the same size and rules as required for a plugin image in the splash screen.` which is incorrect.  The splash screen icons do seem to be 24x24 but the Help About seem like they can use 48x48, confirming David's article link.

**Comment by chuacw** [comment]
The documentation here exists separately from the product's, and so far, consists of my own efforts in reverse engineering.
If the referenced article has a demonstrable example that can be verified, I'll happily add documentation.

If you're expecting the documentation to be updated in the product, please file a request on the [Embarcadero Quality Portal](https://quality.embarcadero.com/secure/Dashboard.jspa).

**Comment by DGH2112** [comment]
The statement "The Image should follow the same size and rules as required for a plugin image in the splash screen" goes all the way back to 2006 (I never had 2005) and it's wrong from 2007 onwards (probably was not amended when the splash screen changed as the about box didn't). For IDEs up to 2006, the splash screen icon was 48x48 but for some reason in 2007 upwards Borland/CodeGear changed it to 24x24. The compiler IFDEFs in the code example shows this.
