### ISSUE TITLE
IOTAAboutBoxServices280 new feature added for TGraphicArray needs extended docs

### ISSUE THREAD

**Issue by darianmiller** [Embarcadero/OTAPI-Docs#4]
There was some documentation notes that I had taken which stated that PNG images are recommended when passing in an array of images.

Please document the PNG preference and suggest which sizes of images should be included.

**Comment by chuacw** [comment]
The documentation here exists separately from the product's, and so far, consists of my own efforts in reverse engineering.

If you're expecting the documentation to be updated in the product, please file a request on the [Embarcadero Quality Portal](https://quality.embarcadero.com/secure/Dashboard.jspa).
