### ISSUE TITLE
How to use form inheritance in IOTAModuleCreator.

### ISSUE THREAD

**Issue by giorgiobazzo** [Embarcadero/OTAPI-Docs#5]
This is a question I have, or rather something I've already tried to do but wasn't successful.

Imagine that I have a Form that has some visual components, Panels, Buttons, Edits, etc. And I want to use it as a template to create later forms for my applications, in a similar way to what the "Add to Repository" feature does.

When we add a form to the repository and then create a new form from it, both the implementation in the .pas file and its visual definition in *.dfm are inherited from the ancestral form.
We can observe this when viewing the dfm in text mode, where the word inherited appears in place of object, for the components that were inherited, indicating that these components depend on the base form.

I was unable to have this same effect when registering a Wizard from IOTAModuleCreator. I tried to manipulate the dfm code through the NewFormFile method of IOTAModuleCreator, but the final result is not exactly the same as the dfm string that I pass to the IOTAFile. Even if passing a string that starts with "inherited fmNewForm: TfmBaseForm...", the dfm created by the wizard starts with "object fmNewForm: TfmBaseForm", and this way the .pas file is correct, but the visual components are not inherited , so the class of the new form is correct, but the visual layout is not.

I would like to have the same effect as "Add to Repository" but using IOTAModuleCreator. Is this possible?

**Comment by chuacw** [comment]
This do not provide support for development issues.
